### ISSUE TITLE
pip does not find the package

### ISSUE THREAD

**Issue by Rudloff** [likema/lsb_release_ex#1]
Hello,

I get this error when I try to install the package:

```
pierre@quai10 ~/www> sudo pip install lsb_release_ex
Collecting lsb_release_ex
  Could not find a version that satisfies the requirement lsb_release_ex (from versions: )
No matching distribution found for lsb_release_ex
```

I am running pip 8.1.2 with python 2.7 on Ubuntu 16.04.

**Comment by likema** [comment]
Sorry, I forget to upload the source package.

I have done it just now. Can you try it again?

**Comment by Rudloff** [comment]
It works, thanks!
